# Лаба 9

x^2y''-xy'+y=lnx/x+x/lnx

y(1)=0
y'(2)=1

y'' - y'/x + y/x^2 = lnx/x^3 + 1/xlnx

p = -1/x

q = 1/x^2

f = lnx/x^3 + 1/xlnx

In [295]:
a=1
b=2
A = 0
B = 0
a0 = 1
a1 = 0
b0 = 1
b1 = 0
p = (lambda x: 1/x)
q = (lambda x: 0)
f = (lambda x: 6*np.log(x)/x)

In [296]:
def solve(n):
    h = (b-a)/n
    x = np.linspace(a, b, n+1) 
    coef=[]
    val=[]
    y = np.zeros((n+1))
    y[0]=a0
    coef.append(y)
    val.append(0)
    for i in range(1,n):
        y = np.zeros((n+1))
        pi = p(x[i])
        qi = q(x[i])
        fi = f(x[i])
        y[i-1]=(1 - h/2 *p(x[i]))
        y[i]=-(2 - h**2*q(x[i]))
        y[i+1]=(1 + h/2 *p(x[i]))
        coef.append(y)
        val.append(h**2*f(x[i]))
    #P = b1*(2-h**2*q(x[n-1]))/(1-h/2*p(x[n-1])) - 4*b1
    #Q = -b1*(1+h/2*p(x[n-1]))/(1-h/2*p(x[n-1])) + 2*h*b0+3*b1
    #R = 2*B*h - (b1 * h**2 * f(x[n-1]))/(1-h/2*p(x[n-1]))
    #y = np.zeros((n+1))
    #y[n-1]=P
    #y[n]=Q
    #coef.append(y)
    #val.append(R)
    y = np.zeros((n+1))
    y[n]=b0
    coef.append(y)
    val.append(0)
    return coef, val

In [297]:
def loop(delta):
    from prettytable import PrettyTable
    tab = PrettyTable(['n', '2n', 'delta%'])
    tab.add_row([0,0,0])
    n = 5
    n2 = n*2
    t = True 
    while t:
        t = False;
        matr1 = solve(n)
        matr2 = solve(n2)
        res_n = np.linalg.solve(matr1[0],matr1[1])
        res_2n = np.linalg.solve(matr2[0],matr2[1])
        for i in range(1,n):
            diff = np.fabs((res_n[i]-res_2n[2*i])/res_n[i] * 100)
            if diff > delta:
                t = True
            else:
                tab.add_row([format(res_n[i], '.6f'), format(res_2n[2*i], '.6f'),diff])
        if not t:
            tab.add_row([0,0,0])
            print(tab)
            break
    return matr1,matr2,res_n,res_2n   

In [298]:
matr1,matr2,res_n,res_2n=loop(1)

+-----------+-----------+---------------------+
|     n     |     2n    |        delta%       |
+-----------+-----------+---------------------+
|     0     |     0     |          0          |
| -0.119671 | -0.118969 |  0.586840256683311  |
| -0.187272 | -0.186455 | 0.43640082943020914 |
| -0.192025 | -0.191368 |  0.3418218711301321 |
| -0.129864 | -0.129503 | 0.27784408065322314 |
|     0     |     0     |          0          |
+-----------+-----------+---------------------+


In [285]:
np.set_printoptions(precision=4)
for el in matr1[0]:
    print(el)
print('\n',matr1[1])

[1. 0. 0. 0. 0. 0.]
[ 0.9167 -2.      1.0833  0.      0.      0.    ]
[ 0.      0.9286 -2.      1.0714  0.      0.    ]
[ 0.      0.      0.9375 -2.      1.0625  0.    ]
[ 0.      0.      0.      0.9444 -2.      1.0556]
[0. 0. 0. 0. 0. 1.]

 [0, 0.03646431135879093, 0.0576809548493508, 0.07050054438686035, 0.07837155532028255, 0]


In [286]:
np.set_printoptions(precision=2)

for el in matr2[0]:
    print(el)
print('\n',matr2[1])

[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[ 0.95 -2.    1.05  0.    0.    0.    0.    0.    0.    0.    0.  ]
[ 0.    0.96 -2.    1.04  0.    0.    0.    0.    0.    0.    0.  ]
[ 0.    0.    0.96 -2.    1.04  0.    0.    0.    0.    0.    0.  ]
[ 0.    0.    0.    0.96 -2.    1.04  0.    0.    0.    0.    0.  ]
[ 0.    0.    0.    0.    0.97 -2.    1.03  0.    0.    0.    0.  ]
[ 0.    0.    0.    0.    0.    0.97 -2.    1.03  0.    0.    0.  ]
[ 0.    0.    0.    0.    0.    0.    0.97 -2.    1.03  0.    0.  ]
[ 0.    0.    0.    0.    0.    0.    0.    0.97 -2.    1.03  0.  ]
[ 0.    0.    0.    0.    0.    0.    0.    0.    0.97 -2.    1.03]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]

 [0, 0.005198737080235907, 0.009116077839697732, 0.01210911989849959, 0.0144202387123377, 0.016218604324326577, 0.017625136096715087, 0.01872805591984131, 0.019592888830070637, 0.020269070089654572, 0]


In [287]:
np.set_printoptions(precision=5)
res_n

array([ 0.     , -0.11967, -0.18727, -0.19202, -0.12986,  0.     ])

In [288]:
res_2n

array([ 0.     , -0.06479, -0.11897, -0.16006, -0.18646, -0.1971 ,
       -0.19137, -0.16889, -0.1295 , -0.07318,  0.     ])